import { useEffect, useState } from "react";
import { MessageSquare, Trash2, Send } from "lucide-react";
import { useLibrary, repository } from "../context";
import { canManage, type Comment } from "../../../../packages/domain/src";
import { useLocale } from "../i18n/LocaleContext";
export default function Comments({kind,id}:{kind:"book"|"publication";id:string}){
  const {user,role,login,notice,preview}=useLibrary(); const {t,dateLocale}=useLocale(); const [comments,setComments]=useState<Comment[]>([]),[body,setBody]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function load(){if(!repository)return;try{setComments(await repository.comments(kind,id));setError("")}catch{setError(t("common.retry"))}}
  useEffect(()=>{setComments([]);void load()},[kind,id]);
  async function send(e:React.FormEvent){e.preventDefault();if(!repository)return;setBusy(true);try{await repository.addComment(kind,id,body);setBody("");await load();notice(t("comments.publish"))}catch(e){notice(e instanceof Error?e.message:t("common.retry"))}finally{setBusy(false)}}
  async function remove(cid:string){if(!repository||!confirm(t("comments.removeConfirm")))return;try{await repository.deleteComment(cid);await load()}catch{notice(t("common.retry"))}}
  return <section className="comments"><div className="section-title"><h2><MessageSquare size={20}/>{t("comments.title")}</h2><span>{comments.length}</span></div>{error&&<p role="alert">{error} <button onClick={load}>{t("common.retry")}</button></p>}{!comments.length&&!error&&<p className="muted">{t("comments.empty")}</p>}{comments.map((c)=><article className="comment" key={c.id}><div className="avatar">{c.profiles?.avatar_url?<img src={c.profiles.avatar_url} alt="" referrerPolicy="no-referrer"/>:c.profiles?.display_name?.[0]||"L"}</div><div><strong data-no-i18n>{c.profiles?.display_name||t("common.reader")}</strong><time>{new Date(c.created_at).toLocaleDateString(dateLocale)}</time><p data-no-i18n>{c.body}</p></div>{(user?.id===c.user_id||canManage(role))&&<button className="icon-button" aria-label={t("common.remove")} onClick={()=>remove(c.id)}><Trash2 size={16}/></button>}</article>)}{user?<form onSubmit={send}><label htmlFor="comment">{t("comments.yourComment")}</label><textarea id="comment" value={body} onChange={(e)=>setBody(e.target.value)} maxLength={3000} placeholder={t("comments.placeholder")} required/><div className="form-actions"><span className="muted">{body.length}/3.000</span><button className="button primary" disabled={busy||!body.trim()}><Send size={16}/>{busy?t("comments.publishing"):t("comments.publish")}</button></div></form>:<button className="button secondary" onClick={login} disabled={preview}>{t("comments.signIn")}</button>}</section>;
}
