import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { UserRound, ShieldCheck, LogOut, PenLine, Camera } from "lucide-react";
import { useLibrary, repository } from "../context";
import { canManage } from "../../../../packages/domain/src";
import { MAX_AVATAR_BYTES } from "../../../../packages/domain/src/avatar";
import { useLocale } from "../i18n/LocaleContext";
import LocaleFlags from "../i18n/LocaleFlags";
export default function Account(){
  const {user,profile,refreshProfile,role,login,logout,preview,notice}=useLibrary(); const {t}=useLocale();
  const [name,setName]=useState(user?.user_metadata.full_name||""); const [uploading,setUploading]=useState(false); const photoInput=useRef<HTMLInputElement>(null);
  async function changePhoto(file?:File){if(!file||!repository||!user)return;setUploading(true);try{if(file.size>MAX_AVATAR_BYTES)throw new Error("3 MB");await repository.uploadAvatar(await file.arrayBuffer());await refreshProfile();notice(t("account.changePhoto"));}catch(error){notice(error instanceof Error?error.message:"Upload failed");}finally{setUploading(false);if(photoInput.current)photoInput.current.value=""}}
  useEffect(()=>setName(profile?.display_name||user?.user_metadata.full_name||""),[profile?.display_name,user?.id]);
  async function save(e:React.FormEvent){e.preventDefault();try{await repository?.saveProfile({display_name:name.trim()});await refreshProfile();notice(t("account.saveName"));}catch{notice(t("common.retry"))}}
  return <div className="account-page"><div className="eyebrow">{t("account.eyebrow")}</div><h1>{user?t("account.title"):t("account.guestTitle")}</h1><p className="lead">{user?t("account.description"):t("account.guestDescription")}</p><div className="account-card"><div className="account-avatar">{profile?.avatar_url?<img src={profile.avatar_url} alt="" referrerPolicy="no-referrer"/>:<UserRound size={32}/>}</div>{user?<><div className="avatar-upload"><input ref={photoInput} type="file" accept="image/jpeg,image/png,image/webp" hidden aria-label={t("account.changePhoto")} disabled={uploading} onChange={(e)=>void changePhoto(e.target.files?.[0])}/><button className="button secondary" type="button" disabled={uploading} onClick={()=>photoInput.current?.click()}><Camera size={17}/>{uploading?t("account.uploadingPhoto"):t("account.changePhoto")}</button><small>{t("account.photoHint")}</small></div><h2 data-no-i18n>{profile?.display_name||user.user_metadata.full_name||t("common.reader")}</h2><p data-no-i18n>{user.email}</p><span className="badge">{role==="owner"?t("account.owner"):role==="admin"?t("account.admin"):t("account.member")}</span><form onSubmit={save}><label>{t("account.displayName")}<input value={name} maxLength={80} required onChange={(e)=>setName(e.target.value)}/></label><button className="button secondary">{t("account.saveName")}</button></form>{canManage(role)&&<Link className="button primary" to="/admin"><ShieldCheck size={18}/>{t("account.openAdmin")}</Link>}<button className="text-button" onClick={logout}><LogOut size={17}/>{t("account.logout")}</button></>:<><h2>{t("account.welcome")}</h2><p>{t("account.googleProfile")}</p><button className="button google-button" onClick={login} disabled={preview}><img className="google-icon" src="./google.svg" alt="" width="20" height="20"/>{t("account.continueGoogle")}</button></>}</div><LocaleFlags/>{preview&&<Link className="editor-preview-link" to="/editor"><PenLine size={18}/>{t("common.edit")}</Link>}</div>;
}
