import { lazy, Suspense, useState, useEffect } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, BookOpen, ExternalLink, Pencil } from "lucide-react";
import { useLibrary, repository } from "../context";
import { canManage, driveUrl, topicLabelLocalized, bookLanguageLabel } from "../../../../packages/domain/src";
import { ReaderRepository } from "../../../../packages/data/src/reader";
import { useLocale } from "../i18n/LocaleContext";
import BookCover from "../components/BookCover";
import Comments from "../components/Comments";
const PdfReader = lazy(() => import("../components/PdfReader"));
export default function Book() {
  const { id } = useParams(); const { books, role, loading, user } = useLibrary(); const { locale, t } = useLocale();
  const book = books.find((b)=>b.id===id); const [reader,setReader]=useState(false); const [compatible,setCompatible]=useState(false),[progress,setProgress]=useState(0);
  useEffect(()=>{let alive=true;if(repository&&id){const r=new ReaderRepository(repository.client);void Promise.all([r.manifest(id),r.position(id).catch(()=>null)]).then(([m,p])=>{if(alive){setCompatible(m?.processing_status==="ready");let saved=p;try{const local=JSON.parse(localStorage.getItem(`reading:${user?.id||'guest'}:${id}`)||'null');if(local&&(!saved||local.updatedAt>saved.updatedAt))saved=local}catch{}setProgress(saved?.revision===m?.revision?saved?.progress||0:0)}}).catch(()=>{})}return()=>{alive=false}},[id,user?.id]);
  if(loading)return <p>{t("common.loading")}</p>;
  if(!book)return <div className="empty"><h1>{t("book.notFound")}</h1><Link to="/">{t("book.backCollection")}</Link></div>;
  if(reader)return <div className="reader"><div className="reader-toolbar"><button className="button secondary" onClick={()=>setReader(false)}><ArrowLeft size={18}/>{t("common.back")}</button><strong data-no-i18n>{book.title}</strong>{book.source_type==="drive"&&<a className="button secondary" href={driveUrl(book)} target="_blank" rel="noreferrer"><ExternalLink size={16}/><span>{t("book.openDrive")}</span></a>}</div>{book.source_type==="upload"?<Suspense fallback={<p>{t("common.loading")}</p>}><PdfReader book={book}/></Suspense>:<><p className="reader-note">{t("book.readerHint")}</p><iframe src={driveUrl(book,true)} title={book.title} allow="fullscreen" referrerPolicy="no-referrer" allowFullScreen/></>}</div>;
  return <><Link className="back-link" to="/"><ArrowLeft size={16}/>{t("book.backLibrary")}</Link><div className="book-detail"><BookCover book={book}/><div className="book-summary"><div className="pills">{book.topics.map((x)=><span key={x}>{topicLabelLocalized(x, locale)}</span>)}{book.schools.map((x)=><span key={x}>{x}</span>)}</div><h1 data-no-i18n>{book.title}</h1><p className="byline" data-no-i18n>{book.authors.join(", ")||t("common.authorPending")}</p><dl>
    <div><dt>{t("book.translation")}</dt><dd data-no-i18n>{book.translators.join(", ")||t("common.notProvided")}</dd></div><div><dt>{t("book.publication")}</dt><dd>{book.published_date||t("common.notProvided")}</dd></div><div><dt>{t("book.edition")}</dt><dd>{book.edition||t("common.notProvided")}</dd></div><div><dt>{t("book.language")}</dt><dd>{book.language?bookLanguageLabel(book.language,locale):t("common.notProvidedMasc")}</dd></div>{book.translation_date&&<div><dt>{t("book.translationDate")}</dt><dd>{book.translation_date}</dd></div>}
    </dl><div className="form-actions">{compatible&&<Link className="button primary" to={"/livro/"+book.id+"/ler"}><BookOpen size={19}/>{progress>0&&progress<.995?t("book.continueReading",{progress:Math.round(progress*100)}):t("book.readNow")}</Link>}<button className={"button "+(compatible?"secondary":"primary")} onClick={()=>{if(book.source_type==="upload"&&book.file_path&&!book.file_path.endsWith(".pdf")){void repository!.pdfUrl(book).then((url)=>window.open(url,"_blank","noopener"))}else setReader(true)}}><BookOpen size={19}/>{compatible?t("book.openOriginal"):t("book.openBook")}</button>{canManage(role)&&<Link className="button secondary" to={"/admin/livro/"+book.id}><Pencil size={17}/>{t("book.editRecord")}</Link>}</div><p className="source-note">{book.source_type==="upload"?t("book.uploadedSource"):t("book.driveSource")}</p></div></div>{book.description&&<section className="synopsis"><h2>{t("book.about")}</h2><p data-no-i18n>{book.description}</p></section>}<Comments kind="book" id={book.id}/></>;
}
